name: Docker Build and Push
on:
  push:
    branches: [ "qa" ]

jobs:
  deploy-bot-master:

    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}


        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1


        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO_QA}}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REPOSITORY:$IMAGE_TAG


        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO_QA}}
            IMAGE_TAG: latest
          with:
            script: |
              sudo aws configure set aws_access_key_id > echo $AWS_ACCESS_KEY_ID
              sudo aws configure set aws_secret_access_key > echo $AWS_SECRET_ACCESS_KEY
              sudo aws configure set default.region > echo $AWS_REGION
              sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 924126288875.dkr.ecr.us-east-1.amazonaws.com
              if [ "$(sudo docker ps -q | wc -l)" -gt "0" ]; then sudo docker rm -f $(sudo docker ps -q); fi
              if [ "$(sudo docker images -q | wc -l)" -gt "0" ]; then sudo docker rmi -f $(sudo docker images -q); fi
              sudo docker run --restart always -p 5000:5000 -d -v /home/ubuntu/app.log:/app/app.log -m 3g --memory-swap 3g 924126288875.dkr.ecr.us-east-1.amazonaws.com/patent-genie-ml-qa:latest
            host: ${{ secrets.EC2_PUB_IP_QA }}
            username: ubuntu
            key: ${{ secrets.EC2_KEY_QA }}
            port: 22
            envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,ECR_REGISTRY,ECR_REPOSITORY,IMAGE_TAG h
